spring:
  application:
    name: checkout-service

server:
  port: 8081

eureka:
  instance:
    statusPageUrlPath: http://localhost:8081/actuator/info
    healthCheckUrlPath: http://localhost:8081/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

#Information exposed in actuator
info:
  name: checkout-service
  description: checkout microservice
  version: 1.0.0