spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
            
        - id: product-service
          uri: lb://products-service
          predicates:
            - Path=/product

server:
  port: 8889